import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * Created by William Vagharfard on 5/6/16.
 */
public class DisplayMatchesGUI {

    private JPanel matchesPanel;
    private JList studentList;
    private JButton getInfoButton;
    private JButton returnButton;
    private static Student stud;
    private static List<Student> studQueue = new LinkedList<>();


    public DisplayMatchesGUI() {
        $$$setupUI$$$();
        DefaultListModel listModel = new DefaultListModel<>();

        //TODO:
        //TODO: I need to pass in the student list here
        //TODO:

        studQueue = Student.readFile();

        for (Student s : studQueue)
            listModel.addElement(s.getName());


        studentList.setListData(listModel.toArray());

        getInfoButton.addActionListener(e -> {
            studentList.getSelectedValue(); // gets selected student

            StudentMatch.createFrame();  //TODO: here, how to create frame from the selected student???
        });

        returnButton.addActionListener(e -> {
            ((JFrame) matchesPanel.getTopLevelAncestor()).dispose();
            MainMenuGUI.createFrame();

        });
    }

    Student getSelect() {
        return (Student) studentList.getSelectedValue();
    }

    static void createFrame() {
        JFrame frame = new JFrame();
        frame.setContentPane(new DisplayMatchesGUI().matchesPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        createFrame();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        matchesPanel = new JPanel();
        matchesPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Student Matches");
        matchesPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        matchesPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        studentList = new JList();
        matchesPanel.add(studentList, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        getInfoButton = new JButton();
        getInfoButton.setText("Get Information");
        matchesPanel.add(getInfoButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        returnButton = new JButton();
        returnButton.setText("Return");
        matchesPanel.add(returnButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return matchesPanel;
    }
}